---
- name: Generate Python script and copy to node
  template:
    src: check_gmail.py.j2
    dest: /home/pi/check_gmail.py
  become: true

- name: execute
  shell: python3 /home/pi/check_gmail.py 2>&1 &
  become: true
  register: python

- name: output
  debug:
    var: python

- name: Add Python Script to Startup
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/check_gmail.py &
    create: yes
  become: true