---
- name: execute
  vars:
    color: "{{ base_config.color }}"
    brightness: "{{ base_config.brightness }}"
  shell: blinkstick --morph {{ color }} --brightness {{ brightness }}
  register: python
  become: true

- name: output
  debug:
    var: python