---
- name: Change brightness
  shell: blinkstick --set-color {{ base_config.color }} --brightness {{ base_config.brightness }}
  register: python
  become: true

- name: output
  debug:
    var: python