- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '0', hour: '8',  weekday: '*', disabled: 'no', brightness: '70', color: 'green'}
      night: { minute: '0', hour: '21', weekday: '*', disabled: 'no', brightness: '30', color: 'cyan'}
  tasks:
    - name: aliases
      include_role:
        name: aliases
      run_once: true
    
    - name: current user - fetch
      shell: whoami
      register: user

    - name: current user - output
      debug:
        var: user.stdout_lines

    - name: current directory
      shell: pwd
      become: false
      register: dir
      delegate_to: localhost
      run_once: true

    - name: execute
      vars:
        ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
        BLINK_PATH: "{{ dir.stdout }}"
      cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      "ansible-playbook {{ BLINK_PATH }}/main.yaml -i {{ BLINK_PATH }}/inventory/all.yaml -t base-config -e brightness={{ crons[item]['brightness'] }} -e color={{ crons[item]['color'] }}"
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      with_items: "{{ crons.keys() | list }}"
      register: output

    - name: verify
      shell: crontab -l
      register: output

    - name: output
      debug:
        var: output.stdout_lines