- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '*', hour: '*',  weekday: '*', disabled: 'no', job: 'blink-night'}
      night: { minute: '0', hour: '21', weekday: '*', disabled: 'no', job: 'blink-night'}
      rave:  { minute: '0', hour: '17', weekday: '*', disabled: 'no', job: 'blink-rave'}
  tasks:
    - name: aliases
      include_role:
        name: aliases
      run_once: true
    
    - name: current user - fetch
      shell: whoami
      register: user

    - name: current user - output
      debug:
        var: user.stdout_lines

    #- name: generate
    #  vars:
    #    ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
    #    BLINK_PATH: "{{ dir.stdout }}"
    #  blockinfile:
    #    block: '{{ lookup("template", "{{ dir.stdout }}/crons/templates/{{ item }}.j2") }}'
    #    path: "{{ dir.stdout }}/crons/jobs/{{ item }}.sh"
    #    backup: no
    #    create: yes
    #  loop: "{{ crons.keys() | list }}"

    #- name: chmod+x
    #  file: dest=~/crons/{{ item }}.sh mode=a+x
    #  loop: "{{ crons.keys() | list }}"

    - name: execute
      cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      "/bin/bash {{ user.stdout }} {{ crons[item]['job'] }}"
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      with_items: "{{ crons.keys() | list }}"
      register: output

    - name: verify
      shell: crontab -l
      register: output

    - name: output
      debug:
        var: output.stdout_lines