- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '*', hour: '*',  weekday: '*', disabled: 'no', job: 'blink-night'}
      night: { minute: '0', hour: '21', weekday: '*', disabled: 'no', job: 'blink-night'}
      rave:  { minute: '0', hour: '17', weekday: '*', disabled: 'no', job: 'blink-rave'}
  tasks:
    - name: cron - env
      include_role:
        name: aliases
      run_once: true
    
    - name: current user - fetch
      shell: whoami
      register: user

    - name: current user - output
      debug:
        var: user.stdout_lines

    - name: execute
      cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      "{{ crons[item]['job'] }}"
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      register: output
      with_items: "{{ crons.keys() | list }}"

    - name: verify
      shell: crontab -l
      register: output

    - name: output
      debug:
        var: output.stdout_lines
