- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '0', hour: '8',  weekday: '*',   disabled: 'no', tag: 'base-config', brightness: '70', color: 'green' }
      night: { minute: '0', hour: '21', weekday: '*',   disabled: 'no', tag: 'base-config', brightness: '20', color: 'cyan' }
      rave:  { minute: '0', hour: '17', weekday: 'FRI', disabled: 'no', tag: 'rave',        brightness: '80', color: 'cyan' }
  tasks:
    - name: aliases
      include_role:
        name: aliases
      run_once: true

    - name: current user - fetch
      ansible.builtin.shell: whoami
      register: user

    - name: current user - output
      ansible.builtin.debug:
        var: user.stdout_lines

    - name: current directory
      ansible.builtin.shell: pwd
      become: false
      register: dir
      delegate_to: localhost
      run_once: true

    - name: execute
      ansible.builtin.cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      "ansible-playbook {{ BLINK_PATH }}/main.yaml -i {{ BLINK_PATH }}/inventory/all.yaml -t {{ crons[item]['tag'] }} -e brightness={{ crons[item]['brightness'] }} -e color={{ crons[item]['color'] }}"
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      with_items: "{{ crons.keys() | list }}"
      register: output
      vars:
        ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
        BLINK_PATH: "{{ dir.stdout }}"
    - name: verify
      ansible.builtin.shell: crontab -l
      register: output

    - name: output
      ansible.builtin.debug:
        var: output.stdout_lines