- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '*', hour: '*',  weekday: '*', disabled: 'no' }
      night: { minute: '0', hour: '21', weekday: '*', disabled: 'no' }
      rave:  { minute: '0', hour: '17', weekday: '*', disabled: 'no' }
  tasks:
    - name: cron - env
      include_role:
        name: aliases
      run_once: true
    
    - name: cron - get user
      shell: whoami
      register: user

    - name: generate crons
      vars:
        ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
        BLINK_PATH: "{{ dir.stdout }}"
      blockinfile:
        block: '{{ lookup("template", "./crons/{{ item }}.j2") }}'
        path: ~/crons/{{ item }}.sh
        backup: no
        create: yes
      loop: "{{ crons.keys() | list }}"

    - name: chmod+x
      file: dest=~/crons/{{ item }}.sh mode=a+x
      loop: "{{ crons.keys() | list }}"

    - name: set crons
      cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      ~/crons/{{ item }}.sh
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      register: output
      with_items: "{{ crons.keys() | list }}"

    - name: cron - 
      shell: crontab -l
      register: output

    - name: output
      debug:
        var: output.stdout_lines