- hosts: localhost
  become: false
  gather_facts: no
  vars:
    crons:
      day:   { minute: '*', hour: '*',  weekday: '*', disabled: 'no'}
      night: { minute: '0', hour: '21', weekday: '*', disabled: 'no'}
      rave:  { minute: '0', hour: '17', weekday: '*', disabled: 'no'}
  tasks:
    - name: aliases
      include_role:
        name: aliases
      run_once: true
    
    - name: current user - fetch
      shell: whoami
      register: user

    - name: current user - output
      debug:
        var: user.stdout_lines

    - name: current directory
      shell: pwd
      become: false
      register: dir
      delegate_to: localhost
      run_once: true

#    - name: generate
#      vars:
#        ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
#        BLINK_PATH: "{{ dir.stdout }}"
#      blockinfile:
#        block: '{{ lookup("template", "{{ dir.stdout }}/crons/templates/{{ item }}.j2") }}'
#        path: "{{ dir.stdout }}/crons/jobs/{{ item }}.sh"
#        backup: no
#        create: yes
#      loop: "{{ crons.keys() | list }}"
    
#    - name: chmod+x
#      file: dest=~/crons/{{ item }}.sh mode=a+x
#      loop: "{{ crons.keys() | list }}"

    - name: execute
      vars:
        ANSIBLE_CONFIG: "{{ dir.stdout }}/ansible.cfg"
        BLINK_PATH: "{{ dir.stdout }}"
      cron:
        name:     "{{ item }}"
        minute:   "{{ crons[item]['minute'] }}"
        hour:     "{{ crons[item]['hour'] }}"
        weekday:  "{{ crons[item]['weekday'] }}"
        job:      "ansible-playbook {{ BLINK_PATH }}/main.yaml -i {{ BLINK_PATH }}/inventory/all.yaml -t blink-{{ item }}"
        user:     "{{ user.stdout }}"
        disabled: "{{ crons[item]['disabled'] }}"
      with_items: "{{ crons.keys() | list }}"
      register: output

    - name: verify
      shell: crontab -l
      register: output

    - name: output
      debug:
        var: output.stdout_lines