---
- hosts: all
  become: true
  gather_facts: no
  vars:
    base_config: 
      color: blue
      brightness: 50
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  roles:
    - { role: get_info, tags: ["get-info"] }
    - { role: install, tags: ["install"] }
    - { role: base_config, tags: ["base-config"] }
    - { role: cpu_usage, tags: ["cpu-usage"] }
    - { role: internet_status, tags: ["internet-status"] }
    - { role: party, tags: ["party"] }
    - { role: turnoff, tags: ["off"] }