---
- hosts: all
  become: true
  gather_facts: no
  vars:
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  roles:
    - { role: get_info, tags: ["get-info", "install"] }
    - { role: install, tags: ["install"] }
    - { role: cpu_usage, tags: ["cpu-usage", "install"] }
    - { role: internet_status, tags: ["internet-status", "install"] }
    - { role: party, tags: ["party"] }
    - { role: turnoff, tags: ["off"] }