---
- hosts: all
  become: true
  gather_facts: no
  vars:
    python_packages:
      - blinkstick
      - psutil
      - feedparser
    gmail_user: greg.robinson@arctiq.ca
    gmail_pass: jvehuvdadrkjssam
  pre_tasks:
    - name: Install Python Dependancies
      pip: name="{{ item }}"
      become: true
      loop: "{{ python_packages }}"
  roles:
    - get_info
    - cpu_usage
    - internet_status
    - check_gmail