---
- hosts: all
  become: true
  gather_facts: no
  vars:
    base_config: 
      color: green
      brightness: 50
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  pre_tasks:
    - name: BLINK_PATH
      shell: pwd
      register: blinkpath
      delegate_to: localhost
      become: false
  roles:
    - { role: get_info,        tags: ["get-info", "deploy"] }
    - { role: install,         tags: ["install", "deploy"] }
    - { role: cpu_usage,       tags: ["cpu-usage", "deploy"] }
    - { role: internet_status, tags: ["internet-status", "deploy"] }
    - { role: rave,            tags: ["rave"] }
    - { role: base_config,     tags: ["base-config"] }
    - { role: aliases,         tags: ["aliases"], vars: { ANSIBLE_CONFIG: "{{ blinkpath }}/ansible.cfg" } }
    - { role: turnoff,         tags: ["off"] }