---
- hosts: all
  become: true
  gather_facts: no
  vars:
    install_packages: false
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  pre_tasks:
    - name: Install Python Dependancies
      pip:
        name: "{{ item }}"
        executable: pip3
      become: true
      loop: "{{ python_packages }}"
  roles:
    - { role: get_info, tags: ["get_info", "install"] }
    - { role: cpu_usage, tags: ["cpu_usage", "install"] }
    - { role: internet_status, tags: ["internet_status", "install"] }
    - { role: turnoff, tags: ["off"] }