---
- hosts: all
  become: true
  gather_facts: no
  vars:
    color: green
    brightness: 100
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  roles:
    - { role: get_info, tags: ["get-info"] }
    - { role: install, tags: ["install"] }
    - { role: cpu_usage, tags: ["cpu-usage"] }
    - { role: internet_status, tags: ["internet-status"] }
    - { role: party, tags: ["party"] }
    - { role: brightness, tags: ["brightness"] }
    - { role: turnoff, tags: ["off"] }