---
- hosts: all
  become: true
  gather_facts: no
  vars:
    cron: true
    base_config: 
      color: green
      brightness: 50
    python_packages:
      - blinkstick
      - psutil
      - feedparser
      - ansible
  roles:
    - { role: get_info,        tags: ["get-info", "deploy"] }
    - { role: install,         tags: ["install", "deploy"] }
    - { role: cpu_usage,       tags: ["cpu-usage", "deploy"] }
    - { role: internet_status, tags: ["internet-status", "deploy"] }
    - { role: aliases,         tags: ["aliases", "deploy"] }
    - { role: rave,            tags: ["rave"] }
    - { role: base_config,     tags: ["base-config"] }
    - { role: turnoff,         tags: ["off"] }

- name: set crons
  vars:
    cron: true
  import_playbook: cron.yaml
  tags: cron
      