---
- name: generate
  template:
    src: cpu_usage.py
    dest: /home/pi/cpu_usage.py
  become: true

- name: execute
  shell: python3 /home/pi/cpu_usage.py 2>&1 &
  become: true
  register: python

- name: output
  debug:
    var: python

- name: add-to-startup
  lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/cpu_usage.py &
  become: true