---
- name: generate
  template:
    src: off.py
    dest: /home/pi/off.py
  become: true

- name: execute
  shell: python3 /home/pi/off.py 2>&1 &
  register: python
  become: true

- name: output
  debug:
    var: python.stdout_lines