---
- name: generate
  template:
    src: internet_status.py.j2
    dest: /home/pi/internet_status.py
  become: true

- name: execute
  shell: python3 /home/pi/internet_status.py 2>&1 &
  register: python
  become: true

- name: output
  debug:
    var: python

- name: add-to-startup
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/internet_status.py &
    create: yes
  become: true