---
- name: Generate Python script and copy to node
  template:
    src: internet_status.py.j2
    dest: /home/pi/internet_status.py
  become: true

- name: Execute CPU Usage Python Script
  shell: python3 /home/pi/internet_status.py 2>&1 &
  become: true
  register: python

- name: output
  debug:
    var: python

- name: Add Python Script to Startup
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/internet_status.py &
    create: yes
  become: true