- name: Install Python Dependancies
  shell: pip3 install psutil && pip3 install blinkstick
  listen: "install"
  notify: "execute_python"
  become: true

- name: Execute CPU Usage Python Script
  shell: python3 /home/pi/cpu_usage.py
  listen: "execute_python"
  notify: "add_to_startup"
  become: true

- name: Add Python Script to Startup
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/cpu_usage.py &
    create: yes
  listen: "add_to_startup"
  become: true