---
- name: execute
  poll: 0
  raw: blinkstick {{ item }}
  tags: ['party']
  loop:
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick --morph {{ item }}
  tags: ['party']
  loop:
    - cyan
    - pink

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick --blink {{ item }}
  tags: ['party']
  loop:
    - cyan
    - pink

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick {{ item }}
  tags: ['party']
  loop:
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick --morph {{ item }}
  tags: ['party']
  loop:
    - cyan
    - pink

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick --blink {{ item }}
  tags: ['party']
  loop:
    - cyan
    - pink

- name: execute
  poll: 0
  ansible.builtin.raw: blinkstick {{ item }}
  tags: ['party']
  loop:
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random
    - random

- name: reset
  include_role: 
    name: base_config