---
- name: generate
  template:
    src: get_info.py
    dest: /home/pi/get_info.py
  become: true

- name: execute
  shell: python3 /home/pi/get_info.py 2>&1 &
  register: python
  become: true

- name: output
  debug:
    var: python.stdout_lines

- name: add-to-startup
  lineinfile:
    path: /etc/rc.local
    line: python3 /home/pi/get_info.py &
    create: yes
  become: true