---
- name: aliases
  include_role:
    name: aliases
  run_once: true

- name: current user
  shell: whoami
  register: user
  become: false
  delegate_to: localhost
  run_once: true

- name: cron - day
  cron:
    name: "Activate Day Mode"
    minute: "*"
    hour: "02"
    weekday: "0-6"
    job: "blink-day"
    user: "{{ user.stdout }}"
    disabled: "no"
  delegate_to: localhost
  register: output
  run_once: true

- name: cron - night
  cron:
    name: "Activate Night Mode"
    minute: "*"
    hour: "21"
    weekday: "0-6"
    job: "blink-night"
    user: "{{ user.stdout }}"
    disabled: "no"
  delegate_to: localhost
  register: output
  run_once: true

- name: cron - verify
  shell: crontab -l
  delegate_to: localhost
  become: false
  register: output
  run_once: true

- name: output
  debug:
    var: output.stdout_lines
  delegate_to: localhost
  run_once: true
