---
- name: aliases
  include_role:
    name: aliases
  run_once: true

- name: current user
  shell: whoami
  register: user
  become: false
  delegate_to: localhost
  run_once: true

- name: cron - day
  cron:
    name: "Activate Day Mode"
    minute: "0"
    hour: "8"
    weekday: "*"
    job: "blink-night >> /var/log/blink-day.log 2>&1"
    user: "{{ user.stdout }}"
    disabled: "no"
  delegate_to: localhost
  register: output
  run_once: true

- name: cron - night
  cron:
    name: "Activate Night Mode"
    minute: "0"
    hour: "21"
    weekday: "*"
    job: "blink-night >> /var/log/blink-night.log 2>&1"
    user: "{{ user.stdout }}"
    disabled: "no"
  delegate_to: localhost
  register: output
  run_once: true

- name: cron - verify
  shell: crontab -l
  delegate_to: localhost
  become: false
  register: output
  run_once: true

- name: output
  debug:
    var: output.stdout_lines
  delegate_to: localhost
  run_once: true
