name: night

on:
  schedule:
    # 12AM UTC --> 8PM EST
    - cron: '0 0 * * *'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          version: 1.10.2

      - name: Setup SSH
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -x
          hosts=("kube1" "kube2" "kube3" "kube4")
          mkdir -p ~/.ssh
          for i in ${hosts[@]};
          do
            host="${i}.gregnrobinson.github.beta.tailscale.net"
            host6=$(tailscale ip -6 $host)
            ssh-keyscan ${host6} >> ~/.ssh/known_hosts
            printf "%s" "${SSH_KEY}" > ~/.ssh/key
            chmod 600 ~/.ssh/key
            ping -c 3 ${host6}
          done

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2.4.0
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            fd7a:115c:a1e0:ab12:4843:cd96:6264:cd23 serial=BS039450-3.0
            fd7a:115c:a1e0:ab12:4843:cd96:6249:397d serial=BS039442-3.0
            fd7a:115c:a1e0:ab12:4843:cd96:6261:8661 serial=BS039438-3.0
            fd7a:115c:a1e0:ab12:4843:cd96:6262:1a73 serial=BS039441-3.0
            
            [all:vars]
            ansible_user=pi
          options: |
            --verbose
            --tag base-config -e color=blue -e brightness=10

      - name: Confirmation
        run: |
          echo "Tests completed successfully..."