# This is a basic workflow to help you get started with Actions

name: blinkstick-ansible-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/tailscale-deploy-github@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.10.2

      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          hosts=("kube1" "kube2" "kube3" "kube4")
          mkdir -p ~/.ssh
          for i in ${hosts[@]};
          do
            IP="$(tailscale ip -6 ${i})"
            ssh-keyscan ${IP} >> ~/.ssh/known_hosts
            printf "%s" "$SSH_KEY" > ~/.ssh/key
            chmod 600 ~/.ssh/key
            tailscale ping ${IP}
          done
      - name: Run Ansible playbook
        id: ping
        run: | 
          ping kube1.gregnrobinson.github.beta.tailscale.net
          ping kube2.gregnrobinson.github.beta.tailscale.net
          ping kube3.gregnrobinson.github.beta.tailscale.net
          ping kube4.gregnrobinson.github.beta.tailscale.net