# This is a basic workflow to help you get started with Actions

name: blinkstick-ansible-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: omahn/wireguard-ssh-github-action@v1.1
        with:
          # Required. IP address of your WireGuard peer.
          peer_ip: ''
          # Required. SSH public key as a string.
          ssh_public_key: ''
          # Port of WireGuard peer.
          peer_port: '51820'
          # Private IP of GitHub peer.
          github_ip: '192.168.192.1'
          # Seconds to wait for SSH connection.
          ssh_connection_timeout: '300'
          # Seconds to timeout SSH session.
          session_timeout: 3600

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.4.0
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.SSH}}
          inventory: |
            [all]
              192.168.0.81
              192.168.0.82
              192.168.0.83
              192.168.0.84
          options: |
            --verbose
            --tag deploy

      - name: confirmation
        run: |
          echo "Tests completed successfully..."
