# This is a basic workflow to help you get started with Actions

name: blinkstick-ansible-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install wireguard
        run: sudo apt-get install wireguard

      - name: Create wireguard tunnel configuration
        run: |
          sed -i -e "s@{{WIREGUARD_PRIVATE_KEY}}@${{ secrets.WIREGUARD_PRIVATE_KEY }}@" $GITHUB_WORKSPACE/tunnel.conf
          sed -i -e "s@{{WIREGUARD_SERVER_PUBLIC_KEY}}@${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}@" $GITHUB_WORKSPACE/tunnel.conf
          sed -i -e "s@{{WIREGUARD_PRIVATE_IP}}@${{ secrets.WIREGUARD_PRIVATE_IP }}@" $GITHUB_WORKSPACE/tunnel.conf
          sed -i -e "s@{{WIREGUARD_SERVER_ENDPOINT}}@${{ secrets.WIREGUARD_SERVER_ENDPOINT }}@" $GITHUB_WORKSPACE/tunnel.conf
          sudo cp $GITHUB_WORKSPACE/tunnel.conf /etc/wireguard/
      - name: Prepare ssh key for remote login
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.CTX_SERVER_DEPLOY_SECRET }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy the package
        run: |
          wg-quick up tunnel

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.4.0
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.SSH}}
          inventory: |
            [all]
              192.168.0.81
              192.168.0.82
              192.168.0.83
              192.168.0.84
          options: |
            --verbose
            --tag deploy

      - name: confirmation
        run: |
          echo "Tests completed successfully..."
