# This is a basic workflow to help you get started with Actions

name: blinkstick-ansible-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.4.0
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: inventory/all.yaml
          options: |
            --verbose
            --tag deploy

      - name: Run a multi-line script
        run: |
          echo "Tests completed successfully..."
