# This is a basic workflow to help you get started with Actions

name: blinkstick-ansible-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: omahn/wireguard-ssh-github-action@v1.1
        with:
          peer_ip: ${{ secrets.PEER_IP }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          peer_port: ${{ secrets.PEER_PORT }}
          github_ip: ${{ secrets.PRIVATE_IP }}
          ssh_connection_timeout: '300'
          session_timeout: 3600

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.4.0
        with:
          playbook: main.yaml
          directory: ./
          key: ${{secrets.SSH}}
          inventory: |
            [all]
              192.168.0.81
              192.168.0.82
              192.168.0.83
              192.168.0.84
          options: |
            --verbose
            --tag deploy

      - name: confirmation
        run: |
          echo "Tests completed successfully..."
